repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.2.1'
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ['-f', 'requirements.txt', '-o', 'requirements.txt']
