/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "v4.5-dev-3393-g30322ebe3c"
#endif /* AVUTIL_FFVERSION_H */
