# @package _global_

svd:
  penalty: 0
  min_size: 1
  dim: 50
  niters: 4
  powm: false
  proba: 1
  conv_only: false
  convtr: false  # ideally this should be true, but some models were trained with this to false.

optim:
  beta2: 0.9998