# Development notes:
# - To build the snap run `snapcraft clean` and `snapcraft pack --verbose`
# - To install local snap `snap install ./buzz_*.snap --dangerous`
name: buzz
base: core24
version: git
title: Buzz
summary: Buzz, offline audio transcription and translation
website: https://buzzcaptions.com
source-code: https://github.com/chidiwilliams/buzz
issues: https://github.com/chidiwilliams/buzz/issues
contact: https://github.com/chidiwilliams
description: |
  Buzz transcribes and translates audio to text offline using OpenAI's Whisper.
  Import audio and video files into Buzz and export them as TXT, SRT, or VTT files.
  Buzz supports Whisper, Whisper.cpp, Faster Whisper, Whisper-compatible models
  from the Hugging Face repository, and the OpenAI Whisper API.
grade: stable
confinement: strict
license: MIT
icon: buzz/assets/buzz.svg

platforms:
  amd64:

parts:
  buzz:
    plugin: uv
    source: .
    build-snaps:
      - astral-uv
    stage-snaps:
      - astral-uv
    build-packages:
      - wget
      - portaudio19-dev
      - qt6-declarative-dev
      - qt6-multimedia-dev
      - libvulkan-dev
      - ccache
      - cmake
      - python3
    build-environment:
      - UV_PYTHON: python3
      - UV_NO_CACHE: "true"
      - UV_HTTP_TIMEOUT: "120"
    stage-packages:
      - python3
      - libgcc-s1
      - libc6
      # Audio
      - ffmpeg
      - libportaudio2
      - libpulse0
      - libasound2
      - libasound2-plugins
      - libasound2-plugins-extra
      - libyaml-dev
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-base-apps
      - gstreamer1.0-pulseaudio
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer-plugins-good1.0-0
      # Display
      - libxkbcommon-x11-0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-xinerama0
      - libxcb-shape0
      - libxcb-cursor0
      # GPU
      - libglu1-mesa
      - libvulkan1
      - mesa-vulkan-drivers
    override-build: |
      wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | tee /etc/apt/trusted.gpg.d/lunarg.asc
      wget -qO /etc/apt/sources.list.d/lunarg-vulkan-noble.list http://packages.lunarg.com/vulkan/lunarg-vulkan-noble.list
      apt update
      apt install -y vulkan-sdk

      # Clear cache to save space on CI
      apt clean
      
      # Run default build steps  
      craftctl default 
      
      uv cache clean
      uv run pip cache purge
      
      mkdir $CRAFT_PART_INSTALL/buzz
      cp -r $CRAFT_PART_BUILD/buzz $CRAFT_PART_INSTALL/
      
      # Create desktop file
      mkdir -p $CRAFT_PART_INSTALL/usr/share/applications
      cp $CRAFT_PART_BUILD/buzz.desktop $CRAFT_PART_INSTALL/usr/share/applications/
    stage:
      - '*'
    prime:
      - '*'

  gpu-2404:
    after: [ buzz ]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
      # Workaround for https://bugs.launchpad.net/snapd/+bug/2055273
      mkdir -p "${CRAFT_PRIME}/gpu-2404"
    prime:
      - bin/gpu-2404-wrapper

apps:
  buzz:
    extensions:
      - gnome
    command-chain:
      - bin/gpu-2404-wrapper
    command: bin/python -m buzz
    desktop: usr/share/applications/buzz.desktop
    environment:
      PATH: $SNAP/usr/bin:$SNAP/bin:$PATH
      LD_LIBRARY_PATH: $SNAP/lib/python3.12/site-packages/nvidia/cudnn/lib:$SNAP/lib/python3.12/site-packages/PyQt6:$SNAP/lib/python3.12/site-packages/PyQt6/Qt6/lib:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:$SNAP:$LD_LIBRARY_PATH
      PYTHONPATH: $SNAP:$SNAP/lib/python3.12/site-packages/PyQt6:$SNAP/lib/python3.12/site-packages/PyQt6/Qt6/lib:$SNAP/usr/lib/python3/dist-packages:$SNAP/usr/lib/python3.12/site-packages:$SNAP/usr/local/lib/python3.12/dist-packages:$SNAP/usr/lib/python3.12/dist-packages:$PYTHONPATH
      QT_MEDIA_BACKEND: gstreamer
    plugs:
      - x11
      - unity7
      - wayland
      - home
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - removable-media
      - audio-playback
      - audio-record
      - password-manager-service