---
name: Deploy GitHub Pages
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci
        working-directory: docs

      - name: Build website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        working-directory: docs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
